name: build

on:
  pull_request:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Generate .npmrc for pintura package
        env:
          NUMBERS_PQINA_NPM_KEY: ${{ secrets.NUMBERS_PQINA_NPM_KEY }}
        run: npm run preconfig.npmrc

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Ionic
        env:
          NUMBERS_STORAGE_BASE_URL: ${{ secrets.NUMBERS_STORAGE_BASE_URL }}
          NUMBERS_STORAGE_TRUSTED_CLIENT_KEY: ${{ secrets.NUMBERS_STORAGE_TRUSTED_CLIENT_KEY }}
          NUMBERS_BUBBLE_DB_URL: ${{ secrets.NUMBERS_BUBBLE_DB_URL }}
          NUMBERS_BUBBLE_IFRAME_URL: ${{ secrets.NUMBERS_BUBBLE_IFRAME_URL }}
          BUBBLE_API_URL: ${{ secrets.BUBBLE_API_URL }}
          APPS_FLYER_DEV_KEY: ${{ secrets.APPS_FLYER_DEV_KEY }}
          NUMBERS_PQINA_NPM_KEY: ${{ secrets.NUMBERS_PQINA_NPM_KEY }}
        run: npm run build

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # https://github.com/actions/setup-java#supported-distributions
          java-version: '21'

      - name: Build Android
        run: |
          npx cap sync android
          cd android/
          ./gradlew assembleDebug

  ios:
    runs-on: macos-14
    timeout-minutes: 60
    if: github.actor != 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Generate .npmrc for pintura package
        env:
          NUMBERS_PQINA_NPM_KEY: ${{ secrets.NUMBERS_PQINA_NPM_KEY }}
        run: npm run preconfig.npmrc

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Ionic
        env:
          NUMBERS_STORAGE_BASE_URL: ${{ secrets.NUMBERS_STORAGE_BASE_URL }}
          NUMBERS_STORAGE_TRUSTED_CLIENT_KEY: ${{ secrets.NUMBERS_STORAGE_TRUSTED_CLIENT_KEY }}
          NUMBERS_BUBBLE_DB_URL: ${{ secrets.NUMBERS_BUBBLE_DB_URL }}
          NUMBERS_BUBBLE_IFRAME_URL: ${{ secrets.NUMBERS_BUBBLE_IFRAME_URL }}
          BUBBLE_API_URL: ${{ secrets.BUBBLE_API_URL }}
          APPS_FLYER_DEV_KEY: ${{ secrets.APPS_FLYER_DEV_KEY }}
          NUMBERS_PQINA_NPM_KEY: ${{ secrets.NUMBERS_PQINA_NPM_KEY }}
        run: npm run build

      - name: Import the Code-Signing PKCS12 Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Download provisioning profiles
        uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          bundle-id: io.numbersprotocol.capturelite
          profile-type: 'IOS_APP_STORE'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Build iOS
        env:
          GOOGLE_IOS_URL_SCHEME: ${{ secrets.GOOGLE_IOS_URL_SCHEME }}
        run: |
          sed -i '' "s/\$(GOOGLE_IOS_URL_SCHEME)/${GOOGLE_IOS_URL_SCHEME}/g" ios/App/App/info.plist
          npx cap sync ios
          xcodebuild archive -workspace ios/App/App.xcworkspace -scheme App -sdk iphoneos  -configuration Debug -archivePath build/App.xcarchive -showBuildTimingSummary -allowProvisioningUpdates archive

  notification-success:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    needs: [android, ios]

    steps:
      - uses: actions/checkout@v4

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'}}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: 'success'

  notification-failure:
    runs-on: ubuntu-latest
    needs: [android, ios]
    if: ${{ failure() && github.actor != 'dependabot[bot]'}}

    steps:
      - uses: actions/checkout@v4

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'}}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: 'failure'
