name: ios-pre-release

on:
  push:
    branches:
      - ios-build

jobs:
  deploy-testflight:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Import the Code-Signing PKCS12 Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      - uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          bundle-id: io.numbersprotocol.capturelite
          profile-type: 'IOS_APP_STORE'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Check if version has been updated
        id: version_check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Ionic
        if: steps.version_check.outputs.changed == 'true'
        env:
          NUMBERS_STORAGE_BASE_URL: ${{ secrets.NUMBERS_STORAGE_BASE_URL }}
        run: |
          npm install -g @angular/cli
          npm install -g @ionic/cli
          npm install
          npm run test-ci
          npm run build

      - name: Sync Capacitor web assets
        if: steps.version_check.outputs.changed == 'true'
        run: |
          npx cap sync ios --no-build

      - name: Build ios release (archive) (Apple-Store)
        if: steps.version_check.outputs.changed == 'true'
        run: |
          xcodebuild archive -workspace ios/App/App.xcworkspace -scheme App -sdk iphoneos  -configuration Release -archivePath build/App.xcarchive -showBuildTimingSummary  MARKETING_VERSION=${{ steps.version_check.outputs.version }}  CURRENT_PROJECT_VERSION=${{ steps.version_check.outputs.version }}  -allowProvisioningUpdates archive

      - name: Build ios release  (IPA) (Apple-Store)
        if: steps.version_check.outputs.changed == 'true'
        run: |
          xcodebuild -exportArchive -archivePath build/App.xcarchive -exportPath build -exportOptionsPlist ios/App/ExportOptions.plist -allowProvisioningUpdates

      - name: Deploy to  APPSTORE ,bundle (ipa) for  testflight
        uses: Apple-Actions/upload-testflight-build@master
        if: steps.version_check.outputs.changed == 'true'
        with:
          app-path: build/App.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Upload .ipa
        if: steps.version_check.outputs.changed == 'true'
        uses: actions/upload-artifact@v1
        with:
          name: ipa
          path: build/App.ipa

      - name: Upload Archive
        if: steps.version_check.outputs.changed == 'true'
        uses: actions/upload-artifact@v1
        with:
          name: xcarchive
          path: build/App.xcarchive
