name: play-console

on: workflow_dispatch

jobs:
  android-google-play-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Set up JDK
        if: steps.extract_branch.outputs.branch == 'develop'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Ionic
        if: steps.extract_branch.outputs.branch == 'develop'
        env:
          NUMBERS_STORAGE_BASE_URL: ${{ secrets.NUMBERS_STORAGE_BASE_URL }}
        run: |
          npm install -g @angular/cli
          npm install -g @ionic/cli
          npm install
          npm run test-ci
          npm run build

      - name: Build Android release bundle (AAB)
        if: steps.extract_branch.outputs.branch == 'develop'
        run: |
          npx cap sync android
          cd android/
          ./gradlew bundleRelease

      - name: Sign release AAB
        if: steps.extract_branch.outputs.branch == 'develop'
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ./android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Create service_account.json
        if: steps.extract_branch.outputs.branch == 'develop'
        run: echo '${{ secrets.PLAY_CONSOLE_SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Play Store (closed alpha track)
        if: steps.extract_branch.outputs.branch == 'develop'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: io.numbersprotocol.capturelite
          releaseFile: ./android/app/build/outputs/bundle/release/app-release.aab
          track: alpha